Plone 6: Do not fail on startup when registering celery task fails.
I get this on Plone 6.1 when running the tests:

```
$ bin/test
Running collective.documentviewer.testing.DocumentViewer:Functional tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.zope.Startup in 0.063 seconds.
  Set up plone.app.testing.layers.PloneFixture in 1.340 seconds.
  Set up collective.documentviewer.testing.DocumentViewer Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp312/zope.configuration-6.0-py3.12.egg/zope/configuration/xmlconfig.py", line 448, in endElementNS
    self.context.end()
  File "/Users/maurits/shared-eggs/cp312/zope.configuration-6.0-py3.12.egg/zope/configuration/config.py", line 748, in end
    self.stack.pop().finish()
  File "/Users/maurits/shared-eggs/cp312/zope.configuration-6.0-py3.12.egg/zope/configuration/config.py", line 917, in finish
    args = toargs(context, *self.argdata)
  File "/Users/maurits/shared-eggs/cp312/zope.configuration-6.0-py3.12.egg/zope/configuration/config.py", line 1759, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/Users/maurits/shared-eggs/cp312/zope.configuration-6.0-py3.12.egg/zope/configuration/fields.py", line 174, in fromUnicode
    value = self.context.resolve(name)
  File "/Users/maurits/shared-eggs/cp312/zope.configuration-6.0-py3.12.egg/zope/configuration/config.py", line 220, in resolve
    __import__(mname)
  File "/Users/maurits/community/collective.documentviewer/collective/documentviewer/upgrades.py", line 8, in <module>
    from collective.documentviewer.async_utils import queueJob
  File "/Users/maurits/community/collective.documentviewer/collective/documentviewer/async_utils.py", line 40, in <module>
    @task()
  File "/Users/maurits/shared-eggs/cp312/collective.celery-1.1.4-py3.12-macosx-15.6-arm64.egg/collective/celery/__init__.py", line 37, in decorator
    return getCelery().task(base=AfterCommitTask, **task_kw)(new_func)
  File "/Users/maurits/shared-eggs/cp312/collective.celery-1.1.4-py3.12-macosx-15.6-arm64.egg/collective/celery/utils.py", line 98, in getCelery
    _local.celery = _getCelery()
  File "/Users/maurits/shared-eggs/cp312/collective.celery-1.1.4-py3.12-macosx-15.6-arm64.egg/collective/celery/utils.py", line 88, in _getCelery
    del(celery.backend)
  File "/Users/maurits/shared-eggs/cp312/celery-5.5.3-py3.12.egg/celery/local.py", line 155, in __delattr__
    delattr(self._get_current_object(), name)
AttributeError: property 'backend' of 'Celery' object has no deleter
```

Probably some changes in `collective.celery` are needed.
But for our current use case, Celery support is not really needed, so I don't want to look into that.